version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TF_SERVING_URL=http://tf-serving:8501/v1/models/cnn-spm:predict
      - DATABASE_URL=postgresql://user:password@db/spam_api
      - REDIS_URL=redis://redis:6379
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    depends_on:
      - tf-serving
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spam_api
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    ports:
      - "6379:6379"

  tf-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./models/cnn-spm:/models/cnn-spm
    environment:
      - MODEL_NAME=cnn-spm
    command: --rest_api_port=8501
